name: Test GCP Sec Mgr

on:
  push:
    branches: [ "main" ]

jobs:
  job_id:
    name: 'get secrets'
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
  
      - id: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v1'
        with:
          secrets: |-
            token:${{ vars.PROJECT_ID }}/foo/1

      - id: 'query'
        env:
          TOKEN: '${{ steps.secrets.outputs.token }}'
        run: |
          echo $TOKEN